//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APIEntities : DbContext
    {
        public APIEntities()
            : base("name=APIEntities")
        {
            this.SetCommandTimeout(300);
        }

        public void SetCommandTimeout(int timeout)
        {
            var objContext = (this as IObjectContextAdapter).ObjectContext;
            objContext.CommandTimeout = timeout;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<webapi_patient_allergy> webapi_patient_allergy { get; set; }
        public virtual DbSet<webapi_patient_basic_info> webapi_patient_basic_info { get; set; }
        public virtual DbSet<webapi_patient_business_address> webapi_patient_business_address { get; set; }
        public virtual DbSet<webapi_patient_business_phone> webapi_patient_business_phone { get; set; }
        public virtual DbSet<webapi_patient_charges> webapi_patient_charges { get; set; }
        public virtual DbSet<webapi_patient_email_add> webapi_patient_email_add { get; set; }
        public virtual DbSet<webapi_patient_family_history> webapi_patient_family_history { get; set; }
        public virtual DbSet<webapi_patient_home_address> webapi_patient_home_address { get; set; }
        public virtual DbSet<webapi_patient_home_phone> webapi_patient_home_phone { get; set; }
        public virtual DbSet<webapi_patient_medical_history> webapi_patient_medical_history { get; set; }
        public virtual DbSet<webapi_patient_mobile_phone> webapi_patient_mobile_phone { get; set; }
        public virtual DbSet<webapi_patient_previous_surgeries> webapi_patient_previous_surgeries { get; set; }
        public virtual DbSet<webapi_patient_services_availed> webapi_patient_services_availed { get; set; }
    }
}
