//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class charge_type_ref
    {
        public charge_type_ref()
        {
            this.visit_type_ref = new HashSet<visit_type_ref>();
        }

        public virtual ICollection<visit_type_ref> visit_type_ref { get; set; }
        public string charge_type_rcd { get; set; }
        public string name_l { get; set; }
        [JsonIgnore]
        public string name_e { get; set; }
        [JsonIgnore]
        public System.Guid lu_user_id { get; set; }
        [JsonIgnore]
        public System.DateTime lu_updated { get; set; }
        [JsonIgnore]
        public bool must_not_change_flag { get; set; }
        [JsonIgnore]
        public Nullable<short> seq_num { get; set; }
        [JsonIgnore]
        public string active_status { get; set; }

        
    }
}
