//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class country_ref
    {
        public string country_rcd { get; set; }
        public string subregion_type_rcd { get; set; }
        public string idd_calling_code { get; set; }
        public string region_type_rcd { get; set; }
        public string name_e { get; set; }
        [JsonIgnore]
        public string name_l { get; set; }
        [JsonIgnore]
        public System.Guid lu_user_id { get; set; }
        [JsonIgnore]
        public System.DateTime lu_updated { get; set; }
        [JsonIgnore]
        public Nullable<short> seq_num { get; set; }
        [JsonIgnore]
        public bool validate_city_flag { get; set; }
        [JsonIgnore]
        public string active_status { get; set; }
        [JsonIgnore]
        public bool local_address_support_flag { get; set; }
        [JsonIgnore]
        public bool must_not_change_flag { get; set; }
        [JsonIgnore]
        public short iso_numeric_code { get; set; }
        [JsonIgnore]
        public string address_format { get; set; }
        [JsonIgnore]
        public string iso_two_character_code { get; set; }
        [JsonIgnore]
        public Nullable<System.Guid> address_setting_id { get; set; }
    }
}
