//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class primary_service_ref
    {
        public string primary_service_rcd { get; set; }
        public string name_e { get; set; }
        [JsonIgnore]
        public string name_l { get; set; }
        [JsonIgnore]
        public System.Guid lu_user_id { get; set; }
        [JsonIgnore]
        public System.DateTime lu_updated { get; set; }
        [JsonIgnore]
        public string active_status { get; set; }
        [JsonIgnore] 
        public Nullable<short> seq_num { get; set; }
        [JsonIgnore] 
        public bool must_not_change_flag { get; set; }
    }
}
