//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class visit_type_ref
    {
        public string visit_type_rcd { get; set; }
        public string visit_type_group_rcd { get; set; }
        public string name_l { get; set; }
        [JsonIgnore]
        public string name_e { get; set; }
        [JsonIgnore]
        public Nullable<short> seq_num { get; set; }
        [JsonIgnore]
        public System.DateTime lu_updated { get; set; }
        [JsonIgnore]
        public System.Guid lu_user_id { get; set; }
        [JsonIgnore]
        public string active_status { get; set; }
        [JsonIgnore]
        public bool must_not_change_flag { get; set; }
        [JsonIgnore]
        public bool exclude_from_count_flag { get; set; }
        public string default_charge_type_rcd { get; set; }
        [JsonIgnore]
        public string sequence_number_code { get; set; }
        [JsonIgnore]
        public string visit_code_prefix { get; set; }
        [JsonIgnore]
        public bool er_registration_flag { get; set; }
        [JsonIgnore]
        public bool pre_admit_flag { get; set; }
        [JsonIgnore]
        public bool mandatory_caregiver_roles_flag { get; set; }
        [JsonIgnore]
        public bool auto_close_visits_flag { get; set; }
        [JsonIgnore]
        public bool reference_visit_flag { get; set; }

        public virtual charge_type_ref charge_type_ref { get; set; }
    }
}
