//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class webapi_patient_medical_history
    {
        public System.Guid patient_id { get; set; }
        public string hospital_number { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> registration_date { get; set; }
        public string medical_history { get; set; }
    }
}
