//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webapi_patient_allergy
    {
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> patient_allergy_id { get; set; }
        public string hospital_number { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string allergen { get; set; }
        public string allergen_type_rcd { get; set; }
        public string allergen_type { get; set; }
        public string allergy_status_rcd { get; set; }
        public string allergen_status { get; set; }
        public string allergy_info_source_rcd { get; set; }
        public string allergy_info_source { get; set; }
        public string allergy_reaction_rcd { get; set; }
        public string allergy_reaction { get; set; }
    }
}
