//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webapi_patient_services_availed
    {
        public string charge_type_rcd { get; set; }
        public System.Guid patient_visit_id { get; set; }
        public System.Guid patient_id { get; set; }
        public string hospital_number { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string primary_service_rcd { get; set; }
        public string primary_service_name { get; set; }
        public string visit_type_rcd { get; set; }
        public string visit_type_name { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> Date_of_Availment { get; set; }
        public Nullable<System.TimeSpan> Time_of_Availment { get; set; }
    }
}
