//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webapi_patient_home_address
    {
        public System.Guid patient_id { get; set; }
        public string hospital_number { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string residence_country_rcd { get; set; }
        public string residence_country_name { get; set; }
        public string home_address_postcode { get; set; }
        public string home_address_address_line_1 { get; set; }
        public string home_address_address_line_2 { get; set; }
        public string home_address_address_line_3 { get; set; }
        public string home_address_sub_region { get; set; }
        public string home_address_sub_region_name { get; set; }
        public string home_address_region { get; set; }
        public string home_address_region_name { get; set; }
        public string home_address_city { get; set; }
        public string home_address_city_name { get; set; }
        public string home_address_country_rcd { get; set; }
        public string home_address_country_name { get; set; }
        public Nullable<System.DateTime> home_address_effective_from_date { get; set; }
        public Nullable<System.DateTime> home_address_effective_until_date { get; set; }
    }
}
